routes/web.php
<?php

use App\Http\Controllers\dashboard\BlogsController;
use App\Http\Controllers\dashboard\ContactsController;
use App\Http\Controllers\dashboard\PagesController;
use App\Http\Controllers\dashboard\ProductsConttoller;
use App\Http\Controllers\dashboard\SettingsConttoller;
use App\Http\Controllers\dashboard\SlidesController;
use App\Http\Controllers\dashboard\UsersController;
use App\Http\Controllers\PagesController as ControllersPagesController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('',[ControllersPagesController::class,'index']);
Route::get('paraiba',[ControllersPagesController::class,'paraiba'])->name('paraiba');
Route::get('site',[ControllersPagesController::class,'site'])->name('site');
Route::get('empresa',[ControllersPagesController::class,'empresa'])->name('empresa');
Route::post('contato',[ControllersPagesController::class,'contato'])->name('contato');
Route::get('politicas-de-privacidade', [ControllersPagesController::class, 'lgpd'])->name('lgpd');


Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix' => 'dashboard' ,'as' => 'dashboard.','middleware' => 'auth'], function () {

	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\dashboard\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\dashboard\ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\dashboard\ProfileController@password']);

	Route::resources([
		'slides'	=> SlidesController::class,
		'blog' 		=> BlogsController::class,
		'pages' 	=> PagesController::class,
		'settings' 	=> SettingsConttoller::class,
		'products' 	=> ProductsConttoller::class,
		'contacts' 	=> ContactsController::class,
		'users' 	=> UsersController::class
	]);

});

app/Http/Livewire/Blogs.php
<?php

namespace App\Http\Livewire;

use App\Models\Blogs as ModelsBlogs;
use Livewire\Component;
use Livewire\WithPagination;

class Blogs extends Component
{
    use WithPagination;

    public $search;
    protected $queryString = ['search'];
    protected $paginationTheme = 'bootstrap';
    
    public function render()
    {
        return view('livewire.blogs',[
            'items' => ModelsBlogs::where('title', 'like', '%'.$this->search.'%')
                        ->orderBy('created_at','asc')
                            ->paginate(15)
        ]);
    }
}

app/Http/Livewire/Contacts.php
<?php

namespace App\Http\Livewire;

use App\Models\Contacts as ModelsContacts;
use Livewire\Component;
use Livewire\WithPagination;

class Contacts extends Component
{
    use WithPagination;

    public $search;
    protected $queryString = ['search'];
    protected $paginationTheme = 'bootstrap';

    public function render()
    {
        return view('livewire.contacts',[
            'items' => ModelsContacts::where('name', 'like', '%'.$this->search.'%')
                        ->orderBy('created_at','asc')->paginate(15)
        ]);
    }
}

app/Http/Livewire/Delete.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Delete extends Component
{
    public $route;

    function formButton($url, $text, $method_field = false, $method = 'POST', $class = 'dropdown-item')
    {
        $formName = 'doc_' . md5(microtime());
        $csrf_field = csrf_field();

        if($method_field == 'DELETE') {
            $method_field = method_field('DELETE');
            $onclick = 'if (confirm(\'Você realmente deseja remover o registro?\')) { document.' . $formName . '.submit(); } event.returnValue = false; return false;';

        } else {
            $method_field = '';
            $onclick = 'document.' . $formName . '.submit()';
        }

        $form = 
        <<<HTML
                <form name="$formName" method="$method" action="$url">
                    $csrf_field
                    $method_field
                </form>
                <a href="#" class="$class" onclick="$onclick"><i class="fas fa-trash"></i>$text</a>
        HTML;

        return $form;
    }

    public function render()
    {
        return <<<'blade'
            <div>
                {!! $this->formButton($this->route, 'Remover', 'DELETE') !!}
            </div>
        blade;
    }
}

app/Http/Livewire/Pages.php
<?php

namespace App\Http\Livewire;

use App\Models\Pages as ModelsPages;
use Livewire\Component;
use Livewire\WithPagination;

class Pages extends Component
{
    use WithPagination;

    public $search;
    protected $queryString = ['search'];
    protected $paginationTheme = 'bootstrap';
    
    public function render()
    {
        return view('livewire.pages',[
            'items' => ModelsPages::where('title', 'like', '%'.$this->search.'%')
                        ->orderBy('created_at','asc')
                            ->paginate(15)
        ]);
    }
}

app/Http/Livewire/Products.php
<?php

namespace App\Http\Livewire;

use App\Models\Products as ModelsProducts;
use Livewire\Component;
use Livewire\WithPagination;

class Products extends Component
{
    use WithPagination;

    public $search;
    protected $queryString = ['search'];
    protected $paginationTheme = 'bootstrap';
    
    public function render()
    {
        return view('livewire.products',[
            'items' => ModelsProducts::where('title', 'like', '%'.$this->search.'%')
                        ->orderBy('created_at','asc')
                            ->paginate(15)
        ]);
    }
}

app/Http/Livewire/Settings.php
<?php

namespace App\Http\Livewire;

use App\Models\Settings as ModelsSettings;
use Livewire\Component;
use Livewire\WithPagination;

class Settings extends Component
{
    use WithPagination;

    public $search;
    protected $queryString = ['search'];
    protected $paginationTheme = 'bootstrap';
    
    public function render()
    {
        return view('livewire.settings',[
            'items' => ModelsSettings::where('title', 'like', '%'.$this->search.'%')
                        ->orderBy('created_at','asc')
                            ->paginate(15)
        ]);
    }
}

app/Http/Livewire/Slides.php
<?php

namespace App\Http\Livewire;

use App\Models\Slides as ModelsSlides;
use Livewire\Component;
use Livewire\WithPagination;

class Slides extends Component
{
    use WithPagination;

    public $search;
    protected $queryString = ['search'];
    protected $paginationTheme = 'bootstrap';

    public function render()
    {
        return view('livewire.slides',[
            'items' => ModelsSlides::where('title', 'like', '%'.$this->search.'%')
                        ->orderBy('created_at','asc')
                            ->paginate(15)
        ]);
    }
}

app/Http/Livewire/Users.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;

class Users extends Component
{
    use WithPagination;

    public $search;
    protected $queryString = ['search'];
    protected $paginationTheme = 'bootstrap';

    public function render()
    {
        return view('livewire.users',[
            'items' => User::where([['name', 'like', '%'.$this->search.'%'], ['id', '!=', auth()->user()->id]])
                        ->orderBy('created_at','asc')
                            ->paginate(15)
        ]);
    }
}

resources/views/livewire/blogs.blade.php
<div class="card w-100">
    <!-- Card header -->
    <div class="card-header border-0">

        <div class="row">
            <div class="col-12 col-sm-3 col-md-3 col-lg-4 col-xl-7">
                <h3 class="mb-0">Adicionar</h3>
            </div>
            <div class="col-8 col-sm-5 col-md-6 col-lg-6 col-xl-4">
                <div id="datatable-basic_filter" class="dataTables_filter">
                    <input wire:model="search" class="form-control form-control-sm" type="text" placeholder="Pesquisar">
                </div>
            </div>
            <div class="col-4 col-md-3 col-lg-2 col-xl-1">
                <a href="{{ route('dashboard.blog.create') }}" class="btn btn-danger btn-sm">Adicionar</a>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table align-items-center table-flush">
            <thead class="thead-light">
                <tr>
                    <th scope="col" class="sort" data-sort="empresa">Image</th>
                    <th scope="col" class="sort" data-sort="empresa">Title</th>
                    <th scope="col" class="sort" data-sort="ativo">Ativo</th>
                    <th scope="col" class="sort" data-sort="cadastro">Cadastro</th>
                    <th scope="col" class="sort" data-sort="cadastro">Atualizado</th>
                    <th scope="col" class="sort" data-sort="opcoes">Opções</th>
                </tr>
            </thead>
            <tbody class="list">
                @foreach ($items as $item)
                    <tr>
                        <th>
                            <img src="{{ Storage::url($item->files->filename) }}" width="200">
                        </th>
                        <td class="budget">
                            {{ $item->title }}
                        </td>
                        <td>
                            <p class="badge badge-{{ $item->active == 1 ? 'success' : 'danger' }}">
                                {{ $item->active == 1 ? 'Ativo' : 'Inativo' }}
                            </p>
                        </td>
                        <td>
                            {{ $item->created_at->format('d-m-Y') }}
                        </td>
                        <td>
                            {{ $item->updated_at->format('d-m-Y') }}
                        </td>
                        <td>
                            <div class="dropdown">
                                <a class="btn" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                    <i class="ni ni-archive-2"></i>Opções
                                </a>
                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                    <a class="dropdown-item" href="{{ route('dashboard.blog.edit', $item) }}">
                                        <i class="fas fa-edit"></i>Editar
                                    </a>
                                    @livewire('delete', ['route' => route('dashboard.blog.destroy',
                                    $item)],key($item->id))
                                </div>
                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <!-- Card footer -->
    <div class="card-footer py-4">
        {{ $items->links() }}
    </div>
</div>

resources/views/livewire/contacts.blade.php
<div class="card w-100">
    <!-- Card header -->
    <div class="card-header border-0">

        <div class="row">
            <div class="col-12 col-sm-5 col-md-8">
                <h3 class="mb-0">Lista</h3>
            </div>
            <div class="col-8 col-sm-7 col-md-4">
                <div id="datatable-basic_filter" class="dataTables_filter">
                    <input wire:model="search" class="form-control form-control-sm" type="text" placeholder="Pesquisar">
                </div>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table align-items-center table-flush">
            <thead class="thead-light">
                <tr>
                    <th scope="col" class="sort" data-sort="empresa">Nome</th>
                    <th scope="col" class="sort" data-sort="empresa">Contato</th>
                    <th scope="col" class="sort" data-sort="empresa">Mensagem</th>
                    <th scope="col" class="sort" data-sort="cadastro">Cadastro</th>
                    <th scope="col" class="sort" data-sort="opcoes">Opções</th>
                </tr>
            </thead>
            <tbody class="list">
                @foreach ($items as $item)
                    <tr style="{{ $item->read == '0' ? 'font-weight: bold;' : '' }}"> 
                        <td class="budget">
                            {{ $item->name }}
                        </td>
                        <td class="budget">
                            {{ $item->phone }}
                        </td>
                        <td class="budget">
                            {{ Str::limit($item->message, 100) }}
                        </td>
                        <td>
                            {{ $item->created_at->format('d-m-Y') }}
                        </td>
                        <td>
                            <div class="dropdown">
                                <a class="btn" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                    <i class="ni ni-archive-2"></i>Opções
                                </a>
                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                    <a class="dropdown-item" href="{{ route('m3.contacts.show', $item) }}">
                                        <i class="fas fa-edit"></i>Ver
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <!-- Card footer -->
    <div class="card-footer py-4">
        {{ $items->links() }}
    </div>
</div>

resources/views/livewire/pages.blade.php
<div class="card w-100">
    <!-- Card header -->
    <div class="card-header border-0">

        <div class="row">
            <div class="col-12 col-sm-3 col-md-3 col-lg-4 col-xl-7">
                <h3 class="mb-0">Lista</h3>
            </div>
            <div class="col-8 col-sm-5 col-md-6 col-lg-6 col-xl-4">
                <div id="datatable-basic_filter" class="dataTables_filter">
                    <input wire:model="search" class="form-control form-control-sm" type="text" placeholder="Pesquisar">
                </div>
            </div>
            <div class="col-4 col-md-3 col-lg-2 col-xl-1">
                <a href="{{ route('dashboard.pages.create') }}" class="btn btn-danger btn-sm">Adicionar</a>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table align-items-center table-flush">
            <thead class="thead-light">
                <tr>
                    <th scope="col" class="sort" data-sort="empresa">Image</th>
                    <th scope="col" class="sort" data-sort="empresa">Title</th>
                    <th scope="col" class="sort" data-sort="empresa">Slug</th>
                    {{-- <th scope="col" class="sort" data-sort="usuario">Position</th> --}}
                    {{-- <th scope="col" class="sort" data-sort="ativo">Ativo</th> --}}
                    <th scope="col" class="sort" data-sort="cadastro">Cadastro</th>
                    <th scope="col" class="sort" data-sort="cadastro">Atualizado</th>
                    <th scope="col" class="sort" data-sort="opcoes">Opções</th>
                </tr>
            </thead>
            <tbody class="list">
                @foreach ($items as $item)
                    <tr>
                        <th>
                            <img src="{{ Storage::url($item->files->filename) }}" width="200">
                        </th>
                        <td class="budget">
                            {{ $item->title }}
                        </td>
                        <td class="budget">
                            {{ $item->slug }}
                        </td>
                        {{-- <td class="budget">
                            {{ $item->position }}
                        </td> --}}
                        {{-- <td>
                            <p class="badge badge-{{ $item->active == 1 ? 'success' : 'danger' }}">
                                {{ $item->active == 1 ? 'Ativo' : 'Inativo' }}
                            </p>
                        </td> --}}
                        <td>
                            {{ $item->created_at->format('d-m-Y') }}
                        </td>
                        <td>
                            {{ $item->updated_at->format('d-m-Y') }}
                        </td>
                        <td>
                            <div class="dropdown">
                                <a class="btn" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                    <i class="ni ni-archive-2"></i>Opções
                                </a>
                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                    <a class="dropdown-item" href="{{ route('dashboard.pages.edit', $item) }}">
                                        <i class="fas fa-edit"></i>Editar
                                    </a>
                                    @livewire('delete', ['route' => route('dashboard.pages.destroy',
                                    $item)],key($item->id))
                                </div>
                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <!-- Card footer -->
    <div class="card-footer py-4">
        {{ $items->links() }}
    </div>
</div>

resources/views/livewire/products.blade.php
<div class="card w-100">
    <!-- Card header -->
    <div class="card-header border-0">

        <div class="row">
            <div class="col-12 col-sm-3 col-md-3 col-lg-4 col-xl-7">
                <h3 class="mb-0">Lista</h3>
            </div>
            <div class="col-8 col-sm-5 col-md-6 col-lg-6 col-xl-4">
                <div id="datatable-basic_filter" class="dataTables_filter">
                    <input wire:model="search" class="form-control form-control-sm" type="text" placeholder="Pesquisar">
                </div>
            </div>
            <div class="col-4 col-md-3 col-lg-2 col-xl-1">
                <a href="{{ route('dashboard.products.create') }}" class="btn btn-danger btn-sm">Adicionar</a>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table align-items-center table-flush">
            <thead class="thead-light">
                <tr>
                    <th scope="col" class="sort" data-sort="empresa">Image</th>
                    <th scope="col" class="sort" data-sort="empresa">Title</th>
                    <th scope="col" class="sort" data-sort="usuario">Valor</th>
                    {{-- <th scope="col" class="sort" data-sort="ativo">Ativo</th> --}}
                    <th scope="col" class="sort" data-sort="cadastro">Cadastro</th>
                    <th scope="col" class="sort" data-sort="cadastro">Atualizado</th>
                    <th scope="col" class="sort" data-sort="opcoes">Opções</th>
                </tr>
            </thead>
            <tbody class="list">
                @foreach ($items as $item)
                    <tr>
                        <th>
                            <img src="{{ Storage::url($item->files->filename) }}" width="200">
                        </th>
                        <td class="budget">
                            {{ $item->title }}
                        </td>
                        <td class="budget">
                            {{ $item->value }}
                        </td>
                        {{-- <td class="budget">
                            {{ $item->position }}
                        </td> --}}
                        {{-- <td>
                            <p class="badge badge-{{ $item->active == 1 ? 'success' : 'danger' }}">
                                {{ $item->active == 1 ? 'Ativo' : 'Inativo' }}
                            </p>
                        </td> --}}
                        <td>
                            {{ $item->created_at->format('d-m-Y') }}
                        </td>
                        <td>
                            {{ $item->updated_at->format('d-m-Y') }}
                        </td>
                        <td>
                            <div class="dropdown">
                                <a class="btn text-danger" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                    <i class="ni ni-archive-2"></i>Opções
                                </a>
                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                    <a class="dropdown-item" href="{{ route('dashboard.products.edit', $item) }}">
                                        <i class="fas fa-edit"></i>Editar
                                    </a>
                                    @livewire('delete', ['route' => route('dashboard.products.destroy',
                                    $item)],key($item->id))
                                </div>
                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <!-- Card footer -->
    <div class="card-footer py-4">
        {{ $items->links() }}
    </div>
</div>

resources/views/livewire/slides.blade.php
<div class="card w-100">
    <!-- Card header -->
    <div class="card-header border-0">

        <div class="row">
            <div class="col-12 col-sm-3 col-md-3 col-lg-4 col-xl-7">
                <h3 class="mb-0">Adicionar</h3>
            </div>
            <div class="col-8 col-sm-5 col-md-6 col-lg-6 col-xl-4">
                <div id="datatable-basic_filter" class="dataTables_filter">
                    <input wire:model="search" class="form-control form-control-sm" type="text" placeholder="Pesquisar">
                </div>
            </div>
            <div class="col-4 col-md-3 col-lg-2 col-xl-1">
                <a href="{{ route('dashboard.slides.create') }}" class="btn btn-danger btn-sm">Adicionar</a>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table align-items-center table-flush">
            <thead class="thead-light">
                <tr>
                    <th scope="col" class="sort" data-sort="empresa">Image</th>
                    <th scope="col" class="sort" data-sort="empresa">Title</th>
                    <th scope="col" class="sort" data-sort="usuario">Position</th>
                    <th scope="col" class="sort" data-sort="ativo">Ativo</th>
                    <th scope="col" class="sort" data-sort="ativo">Incio</th>
                    <th scope="col" class="sort" data-sort="ativo">Término</th>
                    <th scope="col" class="sort" data-sort="cadastro">Cadastro</th>
                    <th scope="col" class="sort" data-sort="cadastro">Atualizado</th>
                    <th scope="col" class="sort" data-sort="opcoes">Opções</th>
                </tr>
            </thead>
            <tbody class="list">
                @foreach ($items as $item)
                    <tr>
                        <th>
                            <img src="{{ Storage::url($item->files->filename) }}" width="200">
                        </th>
                        <td class="budget">
                            {{ $item->title }}
                        </td>
                        <td class="budget">
                            {{ $item->position }}
                        </td>
                        <td>
                            <p class="badge badge-{{ $item->active == 1 ? 'success' : 'danger' }}">
                                {{ $item->active == 1 ? 'Ativo' : 'Inativo' }}
                            </p>
                        </td>
                        <td>
                            {{ date('d-m-Y', strtotime($item->start_at)) }}
                        </td>
                        <td>
                            {{ date('d-m-Y', strtotime($item->finish_at)) }}
                        </td>
                        <td>
                            {{ $item->created_at->format('d-m-Y') }}
                        </td>
                        <td>
                            {{ $item->updated_at->format('d-m-Y') }}
                        </td>
                        <td>
                            <div class="dropdown">
                                <a class="btn text-danger" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                    <i class="ni ni-archive-2"></i>Opções
                                </a>
                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                    <a class="dropdown-item" href="{{ route('dashboard.slides.edit', $item) }}">
                                        <i class="fas fa-edit"></i>Editar
                                    </a>
                                    @livewire('delete', ['route' => route('dashboard.slides.destroy',
                                    $item)],key($item->id))
                                </div>
                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <!-- Card footer -->
    <div class="card-footer py-4">
        {{ $items->links() }}
    </div>
</div>

resources/views/livewire/users.blade.php
<div class="card w-100">
    <!-- Card header -->
    <div class="card-header border-0">

        <div class="row">
            <div class="col-12 col-sm-3 col-md-3 col-lg-4 col-xl-7">
                <h3 class="mb-0">Lista</h3>
            </div>
            <div class="col-8 col-sm-5 col-md-6 col-lg-6 col-xl-4">
                <div id="datatable-basic_filter" class="dataTables_filter">
                    <input wire:model="search" class="form-control form-control-sm" type="text" placeholder="Pesquisar">
                </div>
            </div>
            <div class="col-4 col-md-3 col-lg-2 col-xl-1">
                <a href="{{ route('dashboard.users.create') }}" class="btn btn-danger btn-sm">Adicionar</a>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table align-items-center table-flush">
            <thead class="thead-light">
                <tr>
                    <th scope="col" class="sort" data-sort="empresa">Image</th>
                    <th scope="col" class="sort" data-sort="empresa">Nome</th>
                    <th scope="col" class="sort" data-sort="usuario">E-mail</th>
                    <th scope="col" class="sort" data-sort="ativo">Ativo</th>
                    <th scope="col" class="sort" data-sort="cadastro">Cadastro</th>
                    <th scope="col" class="sort" data-sort="cadastro">Atualizado</th>
                    <th scope="col" class="sort" data-sort="opcoes">Opções</th>
                </tr>
            </thead>
            <tbody class="list">
                @foreach ($items as $item)
                    <tr>
                        <th>
                            <img src="{{ Storage::url($item->hasfiles->file->filename) }}" width="200">
                        </th>
                        <td class="budget">
                            {{ $item->name }}
                        </td>
                        <td class="budget">
                            {{ $item->email }}
                        </td>
                        <td>
                            <p class="badge badge-{{ $item->active == 1 ? 'success' : 'danger' }}">
                                {{ $item->active == 1 ? 'Ativo' : 'Inativo' }}
                            </p>
                        </td>
                        <td>
                            {{ $item->created_at->format('d-m-Y') }}
                        </td>
                        <td>
                            {{ $item->updated_at->format('d-m-Y') }}
                        </td>
                        <td>
                            <div class="dropdown">
                                <a class="btn text-danger" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                    <i class="ni ni-archive-2"></i>Opções
                                </a>
                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                    <a class="dropdown-item" href="{{ route('dashboard.users.edit', $item) }}">
                                        <i class="fas fa-edit"></i>Editar
                                    </a>
                                    @livewire('delete', ['route' => route('dashboard.users.destroy',$item)],key($item->id))
                                </div>
                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <!-- Card footer -->
    <div class="card-footer py-4">
        {{ $items->links() }}
    </div>
</div>